# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ category: 'Star Wars' }, { category: 'Lord of the Rings' }])
#   Character.create(category: 'Luke', movie: movies.first)

american = Category.create(category: "American")
asian = Category.create(category: "Asian")
bbq = Category.create(category: "BBQ")
bar = Category.create(category: "Bar")
bagles = Category.create(category: "Bagels")
bakery = Category.create(category: "Bakery")
bowls = Category.create(category: "Bowls")
breakfast = Category.create(category: "Breakfast")
cafe = Category.create(category: "Cafe")
cakes = Category.create(category: "Cakes")
caribbean = Category.create(category: "Caribbean")
chicken = Category.create(category: "Chicken")
coffee_tea = Category.create(category: "Coffee and Tea")
crepes = Category.create(category: "Crepes")
deli = Category.create(category: "Deli")
dessert = Category.create(category: "Dessert")

diner = Category.create(category: "Diner")
fresh_fruits = Category.create(category: "Fresh Fruits")
grill = Category.create(category: "Grill")
hamburgers = Category.create(category: "Hamburgers")
healthy = Category.create(category: "Healthy")
latin_american = Category.create(category: "Latin American")
mediterranean = Category.create(category: "Mediterranean")
mexican = Category.create(category: "Mexican")
noodles = Category.create(category: "Noodles")
pasta = Category.create(category: "Pasta")
pizza = Category.create(category: "Pizza")
ribs = Category.create(category: "Ribs")
salads = Category.create(category: "Salads")
sandwiches = Category.create(category: "Sandwiches")
seafood = Category.create(category: "Seafood")
shakes = Category.create(category: "Shakes")

smoothies = Category.create(category: "Smoothies")
juices = Category.create(category: "Juices")
snacks = Category.create(category: "Snacks")
soup = Category.create(category: "Soup")
steak = Category.create(category: "Steak")
subs = Category.create(category: "Subs")
tacos = Category.create(category: "Tacos")
vegan = Category.create(category: "Vegan")
vegetarian = Category.create(category: "Vegetarian")
waffles = Category.create(category: "Waffles")
wings = Category.create(category: "Wings")
wraps = Category.create(category: "Wraps")

p "#{Category.count} categories created"
